/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LoginForm: typeof import('@/widgets/LoginForm')['LoginForm']
    LoginPage: typeof import('@/pages/LoginPage')['LoginPage']
    PasswordField: typeof import('@/entities/Login')['PasswordField']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextField: typeof import('./../../shared/ui/TextField.vue')['default']
    UsernameField: typeof import('@/entities/Login')['UsernameField']
  }
}
